name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: x86_64-unknown-linux-gnu
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build binary
        run: cargo build
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test
