# This is derived from following reference,
# https://github.com/crate-ci/cargo-release/blob/master/.github/workflows/post-release.yml
name: Release

on:
  push:
    tags:
      - "v*"

env:
  BIN_NAME: spear

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Get release version from the tags
        shell: bash
        if: env.RELEASE_VERSION == ''
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.RELEASE_VERSION }}"
          echo "current dir:"
          pwd
          sudo mkdir /musl-cross
          echo "dir created"
          wget -q --show-progress -P /musl-cross https://musl.cc/arm-linux-musleabihf-cross.tgz
          ls -la /musl-cross
          tar -xf /musl-cross/arm-linux-musleabihf-cross.tgz
          ls -la /musl-cross
          ls -la /musl-cross/arm-linux-musleabihf-cross/bin/
          ls
      - name: Create Github release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          prerelease: true
  build-release:
    name: build-release
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        build: [raspberry-pi, linux]
        include:
          - build: raspberry-pi
            os: ubuntu-latest
            rust: stable
            target: armv7-unknown-linux-musleabihf
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install packages (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends xz-utils liblz4-tool libssl-dev wget build-essential
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - name: Prepare Ubuntu for raspberry-pi cross compile
        if: matrix.build == 'raspberry-pi'
        run: |
          wget -q --show-progress -P /musl-cross https://musl.cc/arm-linux-musleabihf-cross.tgz
          tar -xf /musl-cross/arm-linux-musleabihf-cross.tgz
          ls -la /musl-cross
          ln -s /musl-cross/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc /usr/local/bin/arm-linux-musleabihf-gcc
          cat >>~/.cargo/config.toml <<EOF
          [target.armv7-unknown-linux-musleabihf]
          linker = "arm-linux-musleabihf-gcc"
          echo "content of config.toml :"
          cat ~/.cargo/config.toml
          echo "ls of /usr/local/bin/ :"
          ls -la /usr/local/bin/
          echo "ls of /musl-cross/arm-linux-musleabihf-cross/bin/: "
          ls -la /musl-cross/arm-linux-musleabihf-cross/bin/
          echo "configured"
          EOF
      - name: Build release binary
        run: cargo build --target ${{ matrix.target }} --verbose --release
      - name: Build archive
        shell: bash
        run: |
          outdir="./target/${{ env.TARGET_DIR }}/release"
          staging="${{ env.BIN_NAME }}-${{ needs.create-release.outputs.release_version }}-${{ matrix.target }}"
          mkdir -p "$staging"/complete
          cp {README.md,LICENSE,Settings.toml} "$staging/"
          if [ "${{ matrix.os }}" = "windows-2019" ]; then
            cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}.exe" "$staging/"
            cd "$staging"
            7z a "../$staging.zip" .
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else 
            cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}" "$staging/"
            tar czf "$staging.tar.gz" -C "$staging" .
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi
      - name: Upload release archive
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream